### PR TITLE
Bump to Laravel 11

### PR DESCRIPTION
**Pull request by mkwsra**
Can you please accept this and publish a new tag/version since I need to use this, and thanks for doing it

### CODE REVIEW

**Comment by mkwsra** [comment]
@ArielMejiaDev Any news on this minor PR?

**Comment by ArielMejiaDev** [comment]
@mkwsra Thanks for your PR, currently I would decline it as there were a few more changes in the testing workflow file to keep everything ready for Laravel 11.

I think that you can use it with Laravel 11 now, so thanks

**Comment by mkwsra** [comment]
Thanks to you, and unfortunately I had to do it because I wasn't able to install it with Laravel 11, so can you please push a new release soon?
Thanks for your comment and your efforts and I wish you a great day 🙌

**Comment by mkwsra** [comment]
Oh wow, you did it, thank you so much 👍

**Pull request closed without merging**
